#!/usr/bin/env python3
import sys
import torch
from diffusers import ControlNetModel, StableDiffusionPipeline

CACHE_DIR = "weights-cache"
sys.path.append(".")


controlnet = ControlNetModel.from_pretrained(
        "Nacholmo/controlnet-qr-pattern",  
        torch_dtype=torch.float16,
        force_download=False,
        cache_dir=CACHE_DIR).to("cuda")

controlnet = None

controlnet = ControlNetModel.from_pretrained(
        "monster-labs/control_v1p_sd15_qrcode_monster", 
        torch_dtype=torch.float16,
        force_download=False,
        cache_dir=CACHE_DIR).to("cuda")

controlnet = None

pipe = StableDiffusionPipeline.from_single_file(
        "./weights-cache/models/revAnimated_v122.safetensors",
        torch_dtype=torch.float16,
        cache_dir=CACHE_DIR).to("cuda")

lora_model_file = './weights-cache/Lora/blindbox_v1_mix.safetensors'
pipe.load_lora_weights(lora_model_file, cache_dir=CACHE_DIR)